name: no-build build
on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build nob
        run: ${{ matrix.cc }} -o nob nob.c
      - name: Run nob
        run: ./nob
