name: no-build build
on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          clang -o nob nob.c
          ./nob
      - name: Build how_to-s
        run: |
          cd how_to/
          clang -o nob nob.c
          ./nob
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        run: |
          ${{ matrix.cc }} -o nob nob.c
          ./nob
      - name: Build how_to-s
        run: |
          cd how_to/
          ${{ matrix.cc }} -o nob nob.c
          ./nob
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        shell: cmd
        # cl.exe isn't available as-is in Github images because they don't want
        # to, so we need to pull env vars ourselves. Refs:
        # https://github.com/actions/runner-images/issues/6205#issuecomment-1241573412
        # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#create-your-own-command-prompt-shortcut
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cl.exe ${{ matrix.hotreload }} /Fe:nob nob.c /W4 /D_CRT_SECURE_NO_WARNINGS
          nob.exe
      - name: Build how_to-s
        shell: cmd
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cd how_to/
          cl.exe ${{ matrix.hotreload }} /Fe:nob nob.c /W4 /D_CRT_SECURE_NO_WARNINGS
          nob.exe
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc
      - name: Build nob
        run: gcc -o nob.exe nob.c -Wall -Wextra
      - name: Run nob
        run: ./nob.exe
  msys2-clang64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: git mingw-w64-clang-x86_64-clang
      - name: Build nob
        run: clang -o nob.exe nob.c -Wall -Wextra
      - name: Run nob
        run: ./nob.exe
